### ISSUE TITLE
Error message: 'download' 

### ISSUE THREAD

**Issue by matthewmartinf** [12rambau/planet-order#19]
![Picture1](https://user-images.githubusercontent.com/44436882/122090678-f07cd700-cdff-11eb-9f62-f8068e1887b9.png)

Im trying to download Planet data in the Planet ordering module for this aoi, but get the error message 'download' when I click to download images.  
Any suggestions welcome,
thanks
Matt

**Comment by 12rambau** [comment]
I don't have myself access to this mosaic with my planet key. But what I see on you screenshot is that no images are available on this area in your contract.

At the end of the loading, you should see on the map the mosaic you're about to download and here you have nothing. For example looking at the Maldives I get the following: 

![Capture d’écran 2021-06-16 à 09 48 15](https://user-images.githubusercontent.com/12596392/122180017-58770000-ce88-11eb-97b0-8921172cd437.png)

If you zoom out to the maximum are you seeing the planet overlay elsewhere?

**Comment by 12rambau** [comment]
## conclusion

1/ the mosaics you are trying to display are not provided with vizualzation parameters. In fact in your first screeshot the images are here they are just fully dark because the `rgb` color combo is unrecognized. I've added an extra `default` viz param that should take care of this issue. 

2/ "downloads". when the quads informations are retreived from the server, no download link is provided which can easily be explained by: 

> you don't have the appropriate rights to download this resource. 

## extra explanation 

"2/" was the trickiest part and you are not the only one facing it. I think based on the mosaic that you are trying to access that you didn't registered with the NICFI program but the free trial. The free trial is not including any downloading rights and is not including the NICFI specific mosaics (medres_analytics_). 

To properly register please follow the SEPAL documentation : https://docs.sepal.io/en/latest/setup/register.html#sign-up-for-planet-lab-data and read carefully the module documentation : https://docs.sepal.io/en/latest/modules/dwn/planet_order.html.

If you're using another contract type please check the availability of the images you're trying to download. 

I'm closing it for now, please feel free to reopen it if the problem persists.
