### ISSUE TITLE
Maldives missing from country/ province AOI selection method

### ISSUE THREAD

**Issue by matthewmartinf** [12rambau/planet-order#20]
If possible, Maldives country needs adding as an AOI. 

Thanks :)

**Comment by 12rambau** [comment]
Thank you for notify me, The bug is actually not related to the module itself but the library I'm using to create application. 
The issue is referenced here: https://github.com/12rambau/sepal_ui/issues/211

In the next release of sepal_ui (I hope by the end of the week) the list of GADM country will be updated

**Comment by 12rambau** [comment]
this issue will be solved in the next SEPAL release beginning of next week: 
![Capture d’écran 2021-06-17 à 13 44 34](https://user-images.githubusercontent.com/12596392/122390436-47a2b900-cf72-11eb-9604-598f68358022.png)
