### ISSUE TITLE
are the basemaps/downloads displaced? 

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/planet-order#36]
I'm using this area of interest https://drive.google.com/file/d/1Nh9wPB_vP4cDtQ87i8Ll9N03_fus1E8Q/view?usp=sharing to download a basemap from January 2022, however, it seems like the downloaded asset is pointing to a different location. I've tested comparing with a global basemap + planet analytics product but the displacement is the same. 
Is the app doing a reprojection process? do you mind testing on your side?

![Displacement](https://user-images.githubusercontent.com/12363250/169502589-77f6b0b4-100f-4f59-960a-e2cbb2bf617a.gif)

**Comment by 12rambau** [comment]
The downloading of images is effectively a pain as Planet use a specific gridding system (https://github.com/sepal-contrib/planet-order/blob/0f93013fc0b0abc7f6e431827a7ec17c47ba1da1/component/scripts/mapping.py#L84). I'm surprised because normally I reproject the AOI in 3857 before doing anything. 

I'll test your AOI from my end to figure it out. 

Thank you for reporting

**Comment by 12rambau** [comment]
Did projecting the images worked ?

**Comment by dfguerrerom** [comment]
No, the test I made didn't work when reprojecting.

**Comment by 12rambau** [comment]
I checked with the latest release and the images are well placed on the map with QGIS:

![image](https://user-images.githubusercontent.com/12596392/230630218-f98f3a5a-0135-4391-b385-39f8637af47d.png)

feel free to reopen if you fance this issue again (note that sometimes the images provided by planet are the issue so you need to report to them directly using their user report tool)
