### ISSUE TITLE
not able to visualize or download

### ISSUE THREAD

**Issue by yfinegold** [12rambau/planet-order#41]
The app is not working but I am also trying to understand the added value of this app to the Planet mosaic interface, where you can already download the planet data.

**Comment by 12rambau** [comment]
Regarding the issue, Planet have changed its API last week, I'm running through bugs in every application using it. I already corrected the clip time series, SEPAFE, and alert_module. This one is the next on the list. 

TBH, It has 0 added value right now because I was asked to code it in parallel of Daniel. I was quite surprised when he presented it during the last SEPAL show and tell. Lack of communication upstream I guess. 

In any case and if you really look for added value, this app is not relying on GEE but only on Planet API. It will be more meaningful when you'll be able to download planet level 2 data from the same interface (something that you won't be able to do with the SEPAL implementation).  but that's not a top priority
